-- ALTER PLUGGABLE DATABASE statement examples
-- This statement is not currently supported by the PlSql grammar
-- Pluggable databases were introduced in Oracle 12c for multitenant architecture

-- Unplug a PDB
ALTER PLUGGABLE DATABASE pdb1 UNPLUG INTO '/oracle/data/pdb1.xml';
ALTER PLUGGABLE DATABASE pdb1 UNPLUG INTO '/oracle/data/pdb1.pdb';

-- Open operations
ALTER PLUGGABLE DATABASE pdb2 OPEN;
ALTER PLUGGABLE DATABASE pdb2 OPEN READ ONLY;
ALTER PLUGGABLE DATABASE pdb2 OPEN READ WRITE;
ALTER PLUGGABLE DATABASE pdb2 OPEN READ WRITE FORCE;
ALTER PLUGGABLE DATABASE pdb2 OPEN READ ONLY RESTRICTED;
ALTER PLUGGABLE DATABASE pdb2 OPEN UPGRADE;
ALTER PLUGGABLE DATABASE ALL OPEN;
ALTER PLUGGABLE DATABASE ALL EXCEPT pdb1 OPEN;
ALTER PLUGGABLE DATABASE pdb5 OPEN READ WRITE INSTANCES = ('ORCLDB_1', 'ORCLDB_2');

-- Close operations
ALTER PLUGGABLE DATABASE pdb2 CLOSE;
ALTER PLUGGABLE DATABASE pdb2 CLOSE IMMEDIATE;
ALTER PLUGGABLE DATABASE ALL CLOSE;
ALTER PLUGGABLE DATABASE pdb6 CLOSE RELOCATE TO 'ORCLDB_3';

-- Save and discard state
ALTER PLUGGABLE DATABASE pdb2 SAVE STATE;
ALTER PLUGGABLE DATABASE pdb2 DISCARD STATE;
ALTER PLUGGABLE DATABASE ALL SAVE STATE;

-- Storage limits
ALTER PLUGGABLE DATABASE pdb2 STORAGE (MAXSIZE 500M);
ALTER PLUGGABLE DATABASE pdb2 STORAGE (MAX_SHARED_TEMP_SIZE 100M);
ALTER PLUGGABLE DATABASE pdb2 STORAGE (MAXSIZE UNLIMITED);

-- Default tablespace operations
ALTER PLUGGABLE DATABASE pdb2 DEFAULT TABLESPACE users;
ALTER PLUGGABLE DATABASE pdb2 DEFAULT TEMPORARY TABLESPACE temp;
-- Note: DATAFILE operations are separate from DEFAULT TABLESPACE
ALTER PLUGGABLE DATABASE pdb2 DEFAULT TABLESPACE users;

-- Rename operations
ALTER PLUGGABLE DATABASE pdb2 RENAME GLOBAL_NAME TO pdb_new;

-- Datafile operations
ALTER PLUGGABLE DATABASE pdb3 DATAFILE ALL OFFLINE;
ALTER PLUGGABLE DATABASE pdb3 DATAFILE ALL ONLINE;
ALTER PLUGGABLE DATABASE pdb3 DATAFILE '/u01/oradata/pdb3/system01.dbf' RESIZE 200M;

-- Tempfile operations
ALTER PLUGGABLE DATABASE pdb3 TEMPFILE '/u01/oradata/pdb3/temp01.dbf' RESIZE 100M;

-- Recovery operations
ALTER PLUGGABLE DATABASE pdb2 BEGIN BACKUP;
ALTER PLUGGABLE DATABASE pdb2 END BACKUP;
ALTER PLUGGABLE DATABASE pdb2 ENABLE RECOVERY;
ALTER PLUGGABLE DATABASE pdb2 DISABLE RECOVERY;

-- Logging operations
ALTER PLUGGABLE DATABASE pdb2 ENABLE FORCE LOGGING;
ALTER PLUGGABLE DATABASE pdb2 DISABLE FORCE LOGGING;
-- SUPPLEMENTAL LOG DATA operations are at database level, not PDB level
-- Commented out as it's not valid for PDB
-- ALTER PLUGGABLE DATABASE pdb2 SUPPLEMENTAL LOG DATA;

-- Refresh operations (for PDB snapshots and clones)
ALTER PLUGGABLE DATABASE pdb2 REFRESH;
ALTER PLUGGABLE DATABASE pdb2 REFRESH MODE MANUAL;
ALTER PLUGGABLE DATABASE pdb2 REFRESH MODE EVERY 60 MINUTES;

-- Set time zone
ALTER PLUGGABLE DATABASE pdb2 SET TIME_ZONE = 'America/New_York';
