-- ALTER PROFILE statement examples
-- This statement is not currently supported by the PlSql grammar
-- Profiles control resource limits and password policies

-- Resource limit examples
ALTER PROFILE app_user LIMIT SESSIONS_PER_USER 5;
ALTER PROFILE app_user LIMIT CPU_PER_SESSION 10000;
ALTER PROFILE app_user LIMIT CPU_PER_CALL 3000;
ALTER PROFILE app_user LIMIT CONNECT_TIME 120;
ALTER PROFILE app_user LIMIT IDLE_TIME 30;
ALTER PROFILE app_user LIMIT LOGICAL_READS_PER_SESSION 1000;
ALTER PROFILE app_user LIMIT LOGICAL_READS_PER_CALL 100;
ALTER PROFILE app_user LIMIT COMPOSITE_LIMIT 5000000;
ALTER PROFILE app_user LIMIT PRIVATE_SGA 100K;

-- Set resource limits to unlimited
ALTER PROFILE app_user2 LIMIT IDLE_TIME UNLIMITED;
ALTER PROFILE app_user2 LIMIT SESSIONS_PER_USER UNLIMITED;

-- Set resource limits to default
ALTER PROFILE app_user2 LIMIT CPU_PER_SESSION DEFAULT;
ALTER PROFILE app_user2 LIMIT CONNECT_TIME DEFAULT;

-- Password parameters
ALTER PROFILE app_user LIMIT FAILED_LOGIN_ATTEMPTS 5;
ALTER PROFILE app_user LIMIT PASSWORD_LIFE_TIME 90;
ALTER PROFILE app_user LIMIT PASSWORD_REUSE_TIME 365;
ALTER PROFILE app_user LIMIT PASSWORD_REUSE_MAX 10;
ALTER PROFILE app_user LIMIT PASSWORD_LOCK_TIME 1;
ALTER PROFILE app_user LIMIT PASSWORD_GRACE_TIME 7;
ALTER PROFILE app_user LIMIT PASSWORD_VERIFY_FUNCTION verify_function;
ALTER PROFILE app_user LIMIT PASSWORD_VERIFY_FUNCTION NULL;

-- Combined resource and password limits
ALTER PROFILE app_user LIMIT
  SESSIONS_PER_USER 5
  IDLE_TIME 30
  FAILED_LOGIN_ATTEMPTS 5
  PASSWORD_LIFE_TIME 90
  PASSWORD_GRACE_TIME 5
  PASSWORD_LOCK_TIME 1;

-- Password reuse settings
ALTER PROFILE new_profile LIMIT
  PASSWORD_REUSE_TIME 90
  PASSWORD_REUSE_MAX UNLIMITED;

-- Modify the DEFAULT profile
ALTER PROFILE default LIMIT IDLE_TIME 2;
ALTER PROFILE default LIMIT FAILED_LOGIN_ATTEMPTS 3;

-- Set password parameters to default
ALTER PROFILE app_user LIMIT
  PASSWORD_REUSE_TIME DEFAULT
  PASSWORD_REUSE_MAX DEFAULT;

-- Composite example with multiple parameters
ALTER PROFILE web_user LIMIT
  CPU_PER_SESSION 20000
  SESSIONS_PER_USER 10
  CONNECT_TIME 240
  IDLE_TIME 60
  FAILED_LOGIN_ATTEMPTS 10
  PASSWORD_LIFE_TIME 180
  PASSWORD_GRACE_TIME 10
  PASSWORD_LOCK_TIME 7
  PASSWORD_REUSE_TIME 730
  PASSWORD_REUSE_MAX UNLIMITED;
