-- ALTER TABLE advanced operations
-- Various less common but valid ALTER TABLE operations

-- ALTER TABLE with DEFAULT ON NULL
ALTER TABLE employees MODIFY (salary NUMBER DEFAULT ON NULL 0);
ALTER TABLE employees ADD (bonus NUMBER DEFAULT ON NULL 0);

-- ALTER TABLE with COLLATE
ALTER TABLE products MODIFY (product_name VARCHAR2(100) COLLATE BINARY_CI);
ALTER TABLE customers ADD (email VARCHAR2(100) COLLATE BINARY);

-- Convert non-partitioned table to partitioned (Oracle 12.2+)
ALTER TABLE orders MODIFY
    PARTITION BY RANGE (order_date)
    INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
    (PARTITION p_old VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD')))
    ONLINE
    UPDATE INDEXES;

-- Add column with INVISIBLE attribute
ALTER TABLE employees ADD (ssn VARCHAR2(11) INVISIBLE);

-- Modify column visibility
ALTER TABLE employees MODIFY (ssn VISIBLE);
ALTER TABLE employees MODIFY (ssn INVISIBLE);

-- Add identity column (Oracle 12.1+)
ALTER TABLE legacy_table ADD (
    new_id NUMBER GENERATED BY DEFAULT AS IDENTITY
);

-- Modify identity column options
ALTER TABLE test_table MODIFY (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
    START WITH 1000
    INCREMENT BY 1
);

-- Drop identity clause
ALTER TABLE test_table MODIFY (id DROP IDENTITY);

-- Add virtual column with VIRTUAL keyword
ALTER TABLE employees ADD (
    full_name VARCHAR2(100) GENERATED ALWAYS AS (first_name || ' ' || last_name) VIRTUAL
);

-- Modify existing column to add expression
ALTER TABLE products MODIFY (
    total_price GENERATED ALWAYS AS (unit_price * quantity)
);

-- Add column with CHECK constraint using new syntax
ALTER TABLE orders ADD (
    priority VARCHAR2(10) DEFAULT 'MEDIUM'
    CONSTRAINT chk_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH'))
);

-- Add columns with DEFAULT ON NULL in a single statement
ALTER TABLE config ADD (
    param1 VARCHAR2(50) DEFAULT ON NULL 'DEFAULT1',
    param2 NUMBER DEFAULT ON NULL 0,
    param3 DATE DEFAULT ON NULL SYSDATE
);

-- Modify table to add compression at table level
ALTER TABLE large_table COMPRESS FOR OLTP;
ALTER TABLE archive_table COMPRESS FOR ARCHIVE HIGH;
ALTER TABLE query_table COMPRESS FOR QUERY LOW;

-- Modify table to remove compression
ALTER TABLE hot_table NOCOMPRESS;

-- Convert regular table to Index Organized Table (complex operation)
ALTER TABLE small_table MOVE ORGANIZATION INDEX;

-- Add SUPPLEMENTAL LOG DATA variations
ALTER TABLE audit_table ADD SUPPLEMENTAL LOG DATA;
ALTER TABLE audit_table ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE audit_table ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
ALTER TABLE audit_table ADD SUPPLEMENTAL LOG DATA (UNIQUE) COLUMNS;
ALTER TABLE audit_table ADD SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS;

-- Drop SUPPLEMENTAL LOG DATA
ALTER TABLE audit_table DROP SUPPLEMENTAL LOG DATA;

-- Set UNUSED column (marks for later drop)
ALTER TABLE old_table SET UNUSED (obsolete_col1);
ALTER TABLE old_table SET UNUSED (obsolete_col2, obsolete_col3);
ALTER TABLE old_table SET UNUSED COLUMN old_column CASCADE CONSTRAINTS;

-- Drop UNUSED columns
ALTER TABLE old_table DROP UNUSED COLUMNS;
ALTER TABLE old_table DROP UNUSED COLUMNS CHECKPOINT 1000;

-- Modify collection column (nested table)
ALTER TABLE orders MODIFY NESTED TABLE line_items RETURN AS LOCATOR;
ALTER TABLE orders MODIFY NESTED TABLE line_items RETURN AS VALUE;

-- Add LOB column with specific storage
ALTER TABLE documents ADD (
    content CLOB
) LOB (content) STORE AS SECUREFILE (
    TABLESPACE lob_ts
    ENABLE STORAGE IN ROW
    CHUNK 8192
    CACHE READS
    COMPRESS HIGH
    DEDUPLICATE
);

-- Modify LOB storage
ALTER TABLE documents MODIFY LOB (content) (
    CACHE
    COMPRESS MEDIUM
    KEEP_DUPLICATES
);

-- Add constraint using RELY/NORELY
ALTER TABLE fact_table ADD CONSTRAINT fk_dim
    FOREIGN KEY (dim_id) REFERENCES dimension_table(id)
    RELY DISABLE NOVALIDATE;

-- Add constraint with DEFERRABLE
ALTER TABLE orders ADD CONSTRAINT check_order_total
    CHECK (total >= 0)
    DEFERRABLE INITIALLY DEFERRED;

-- Modify constraint state
ALTER TABLE orders MODIFY CONSTRAINT check_order_total NOT DEFERRABLE;

-- Enable/Disable row movement (required for various operations)
ALTER TABLE partitioned_table ENABLE ROW MOVEMENT;
ALTER TABLE partitioned_table DISABLE ROW MOVEMENT;

-- Modify table monitoring
ALTER TABLE stats_table MONITORING;
ALTER TABLE stats_table NOMONITORING;

-- Modify parallel degree
ALTER TABLE big_table PARALLEL 16;
ALTER TABLE big_table PARALLEL (DEGREE 8 INSTANCES 2);
ALTER TABLE small_table NOPARALLEL;

-- Modify table CACHE attribute
ALTER TABLE frequently_read CACHE;
ALTER TABLE rarely_read NOCACHE;

-- Modify RESULT_CACHE
ALTER TABLE lookup_table RESULT_CACHE (MODE FORCE);
ALTER TABLE lookup_table RESULT_CACHE (MODE DEFAULT);

-- Upgrade table (for edition-based redefinition)
ALTER TABLE app_table UPGRADE INCLUDING DATA;

-- Modify records per block
ALTER TABLE small_records MINIMIZE RECORDS_PER_BLOCK;
ALTER TABLE small_records NOMINIMIZE RECORDS_PER_BLOCK;

-- Rename constraint
ALTER TABLE employees RENAME CONSTRAINT old_name TO new_name;

-- Modify constraint to add/drop CASCADE
ALTER TABLE child_table MODIFY CONSTRAINT fk_parent ON DELETE CASCADE;
ALTER TABLE child_table MODIFY CONSTRAINT fk_parent ON DELETE SET NULL;

-- Add column with domain (Oracle 23ai)
ALTER TABLE employees ADD (
    email_address VARCHAR2(100) DOMAIN email_domain
);
