-- ALTER TABLE with Oracle 23ai new datatypes
-- Testing ADD and MODIFY with JSON, VECTOR, and BOOLEAN datatypes

-- Add JSON column
ALTER TABLE products ADD (product_metadata JSON);

-- Add JSON column with constraint
ALTER TABLE orders ADD (
    order_details JSON,
    CONSTRAINT order_json_valid CHECK (order_details IS JSON)
);

-- Add VECTOR column
ALTER TABLE documents ADD (embedding VECTOR);

-- Add VECTOR column with dimensions
ALTER TABLE documents ADD (
    title_embedding VECTOR(768),
    content_embedding VECTOR(1536)
);

-- Add VECTOR column with specific format
ALTER TABLE embeddings ADD (vec_float32 VECTOR(512, FLOAT32));
ALTER TABLE embeddings ADD (vec_int8 VECTOR(128, INT8));
ALTER TABLE embeddings ADD (vec_binary VECTOR(64, BINARY));

-- Add BOOLEAN column
ALTER TABLE users ADD (is_active BOOLEAN DEFAULT TRUE);

-- Add multiple BOOLEAN columns
ALTER TABLE feature_flags ADD (
    is_enabled BOOLEAN DEFAULT FALSE,
    is_beta BOOLEAN,
    is_deprecated BOOLEAN DEFAULT FALSE
);

-- Add combination of new datatypes
ALTER TABLE products ADD (
    is_available BOOLEAN DEFAULT TRUE,
    specifications JSON,
    image_vector VECTOR(512)
);

-- Modify column to JSON
ALTER TABLE legacy_products MODIFY (specs_text JSON);

-- Modify column to VECTOR
ALTER TABLE documents MODIFY (old_embedding VECTOR(768));

-- Modify column to BOOLEAN
ALTER TABLE users MODIFY (active_flag BOOLEAN);

-- Add NOT NULL constraint to new datatype
ALTER TABLE products MODIFY (product_metadata JSON NOT NULL);

-- Add DEFAULT value for new datatypes
ALTER TABLE settings ADD (
    feature_enabled BOOLEAN DEFAULT FALSE,
    config_data JSON DEFAULT '{}' ON NULL
);

-- Add INVISIBLE column with new datatype
ALTER TABLE audit_log ADD (
    metrics JSON INVISIBLE,
    is_processed BOOLEAN INVISIBLE DEFAULT FALSE
);

-- Rename column with new datatype (to test column operations)
ALTER TABLE temp_table RENAME COLUMN old_json_col TO new_json_col;

-- Drop column with new datatype
ALTER TABLE test_table DROP COLUMN unused_vector;
ALTER TABLE test_table DROP COLUMN (old_json1, old_json2);

-- Add multiple columns including new datatypes
ALTER TABLE comprehensive_test ADD (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    is_active BOOLEAN DEFAULT TRUE,
    metadata JSON,
    embedding VECTOR(768),
    created_date TIMESTAMP DEFAULT SYSTIMESTAMP
);
