-- ALTER SYSTEM statement examples
-- This statement is not currently supported by the PlSql grammar

-- Archive log operations
ALTER SYSTEM ARCHIVE LOG CHANGE 9356083;
ALTER SYSTEM ARCHIVE LOG LOGFILE 'diskl:log6.log' TO 'diska:[arch$]';
ALTER SYSTEM ARCHIVE LOG ALL;
ALTER SYSTEM ARCHIVE LOG CURRENT;

-- Checkpoint operations
ALTER SYSTEM CHECKPOINT;
ALTER SYSTEM CHECKPOINT GLOBAL;
ALTER SYSTEM CHECKPOINT LOCAL;

-- Switch logfile
ALTER SYSTEM SWITCH LOGFILE;

-- Flush operations
ALTER SYSTEM FLUSH SHARED_POOL;
ALTER SYSTEM FLUSH BUFFER_CACHE;
ALTER SYSTEM FLUSH FLASH_CACHE;

-- Set initialization parameters
ALTER SYSTEM SET QUERY_REWRITE_ENABLED = TRUE;
ALTER SYSTEM SET RESOURCE_LIMIT = TRUE;
ALTER SYSTEM SET LICENSE_MAX_SESSIONS = 64;
ALTER SYSTEM SET LICENSE_SESSIONS_WARNING = 54;
ALTER SYSTEM SET LICENSE_MAX_USERS = 200;
ALTER SYSTEM SET SHARED_SERVERS = 25;
ALTER SYSTEM SET DISPATCHERS = '(INDEX=0)(PROTOCOL=TCP)(DISPATCHERS=5)';
ALTER SYSTEM SET LOG_ARCHIVE_DEST_1 = 'LOCATION=/arch/' SCOPE=SPFILE;
ALTER SYSTEM SET PARALLEL_MAX_SERVERS = 20 SCOPE=MEMORY;
ALTER SYSTEM SET DB_CACHE_SIZE = 96M SCOPE=BOTH SID='*';

-- Kill session
ALTER SYSTEM KILL SESSION '39, 23';
ALTER SYSTEM KILL SESSION '39, 23' IMMEDIATE;

-- Disconnect session
ALTER SYSTEM DISCONNECT SESSION '13, 8' POST_TRANSACTION;
ALTER SYSTEM DISCONNECT SESSION '13, 8' IMMEDIATE;

-- Restricted session
ALTER SYSTEM ENABLE RESTRICTED SESSION;
ALTER SYSTEM DISABLE RESTRICTED SESSION;

-- Distributed recovery
ALTER SYSTEM ENABLE DISTRIBUTED RECOVERY;
ALTER SYSTEM DISABLE DISTRIBUTED RECOVERY;

-- Suspend and resume operations
ALTER SYSTEM SUSPEND;
ALTER SYSTEM RESUME;

-- Quiesce operations
ALTER SYSTEM QUIESCE RESTRICTED;
ALTER SYSTEM UNQUIESCE;

-- Register operation
ALTER SYSTEM REGISTER;
