-- CREATE SEQUENCE statement variations
-- Tests CREATE SEQUENCE with various options

-- Basic CREATE SEQUENCE
CREATE SEQUENCE emp_seq;

-- CREATE SEQUENCE with START WITH
CREATE SEQUENCE emp_id_seq START WITH 1000;

-- CREATE SEQUENCE with INCREMENT BY
CREATE SEQUENCE emp_seq_by_10 INCREMENT BY 10;

-- CREATE SEQUENCE with START WITH and INCREMENT BY
CREATE SEQUENCE custom_seq START WITH 100 INCREMENT BY 5;

-- CREATE SEQUENCE with MINVALUE
CREATE SEQUENCE seq_with_min MINVALUE 1;

-- CREATE SEQUENCE with MAXVALUE
CREATE SEQUENCE seq_with_max MAXVALUE 999999;

-- CREATE SEQUENCE with both MINVALUE and MAXVALUE
CREATE SEQUENCE bounded_seq
MINVALUE 1
MAXVALUE 100000;

-- CREATE SEQUENCE with NOMINVALUE
CREATE SEQUENCE seq_no_min NOMINVALUE;

-- CREATE SEQUENCE with NOMAXVALUE
CREATE SEQUENCE seq_no_max NOMAXVALUE;

-- CREATE SEQUENCE with CYCLE
CREATE SEQUENCE cycling_seq
MINVALUE 1
MAXVALUE 100
CYCLE;

-- CREATE SEQUENCE with NOCYCLE (default)
CREATE SEQUENCE nocycle_seq
MINVALUE 1
MAXVALUE 100
NOCYCLE;

-- CREATE SEQUENCE with CACHE
CREATE SEQUENCE cached_seq CACHE 20;

-- CREATE SEQUENCE with larger cache
CREATE SEQUENCE large_cache_seq CACHE 1000;

-- CREATE SEQUENCE with NOCACHE
CREATE SEQUENCE nocache_seq NOCACHE;

-- CREATE SEQUENCE with ORDER
CREATE SEQUENCE ordered_seq ORDER;

-- CREATE SEQUENCE with NOORDER (default)
CREATE SEQUENCE noorder_seq NOORDER;

-- CREATE SEQUENCE with all options
CREATE SEQUENCE comprehensive_seq
START WITH 1000
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999
CYCLE
CACHE 100
ORDER;

-- CREATE SEQUENCE for negative increments (countdown)
CREATE SEQUENCE countdown_seq
START WITH 1000
INCREMENT BY -1
MINVALUE 1
MAXVALUE 1000
CYCLE;

-- CREATE SEQUENCE with large numbers
CREATE SEQUENCE large_num_seq
START WITH 1000000000
INCREMENT BY 1
MAXVALUE 9999999999999999999999999999;

-- CREATE SEQUENCE with schema qualification
CREATE SEQUENCE hr.employee_seq
START WITH 1
INCREMENT BY 1;

-- CREATE SEQUENCE for primary key generation
CREATE SEQUENCE pk_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- CREATE SEQUENCE with small cache
CREATE SEQUENCE small_cache_seq CACHE 2;

-- CREATE SEQUENCE with CACHE 1 (essentially nocache)
CREATE SEQUENCE cache_one_seq CACHE 1;

-- CREATE SEQUENCE for RAC environment with ORDER
CREATE SEQUENCE rac_seq
START WITH 1
INCREMENT BY 1
CACHE 1000
ORDER;

-- CREATE SEQUENCE for global temporary table
CREATE SEQUENCE temp_seq
START WITH 1
INCREMENT BY 1
NOCACHE;

-- CREATE SEQUENCE with specific range
CREATE SEQUENCE year_seq
START WITH 2024
INCREMENT BY 1
MINVALUE 2024
MAXVALUE 2050
NOCYCLE;

-- CREATE SEQUENCE for versioning
CREATE SEQUENCE version_seq
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- CREATE SEQUENCE with increment by 100
CREATE SEQUENCE hundred_seq
START WITH 100
INCREMENT BY 100
NOCYCLE;

-- CREATE SEQUENCE starting from 0
CREATE SEQUENCE zero_start_seq
START WITH 0
INCREMENT BY 1;

-- CREATE SEQUENCE for decreasing values
CREATE SEQUENCE desc_seq
START WITH 10000
INCREMENT BY -10
MINVALUE 1
MAXVALUE 10000
NOCYCLE;

-- CREATE SEQUENCE with cycling for circular buffer
CREATE SEQUENCE circular_buffer_seq
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000
CYCLE
CACHE 10;

-- CREATE SEQUENCE for ticket numbers
CREATE SEQUENCE ticket_seq
START WITH 100000
INCREMENT BY 1
MINVALUE 100000
NOCYCLE
CACHE 50;

-- CREATE SEQUENCE for invoice numbers
CREATE SEQUENCE invoice_seq
START WITH 1
INCREMENT BY 1
NOCYCLE
CACHE 100;

-- CREATE SEQUENCE for batch processing
CREATE SEQUENCE batch_id_seq
START WITH 1
INCREMENT BY 1
NOCACHE
ORDER;

-- CREATE SEQUENCE with MAXVALUE at maximum
CREATE SEQUENCE max_seq
MAXVALUE 9999999999999999999999999999
NOCYCLE;

-- CREATE SEQUENCE with negative MINVALUE
CREATE SEQUENCE negative_seq
START WITH -1000
INCREMENT BY -1
MINVALUE -9999
MAXVALUE -1;

-- CREATE SEQUENCE for both positive and negative
CREATE SEQUENCE signed_seq
START WITH 0
INCREMENT BY 1
MINVALUE -1000
MAXVALUE 1000
CYCLE;

-- CREATE SEQUENCE with ORDER for RAC
CREATE SEQUENCE rac_ordered_seq
START WITH 1
INCREMENT BY 1
CACHE 100
ORDER;

-- CREATE SEQUENCE without ORDER (better performance)
CREATE SEQUENCE noorder_fast_seq
START WITH 1
INCREMENT BY 1
CACHE 1000
NOORDER;

-- CREATE SEQUENCE for partition key
CREATE SEQUENCE partition_key_seq
START WITH 1
INCREMENT BY 1
CACHE 500;

-- CREATE SEQUENCE with all defaults
CREATE SEQUENCE default_seq;

-- CREATE SEQUENCE for timestamp-based ordering
CREATE SEQUENCE time_order_seq
START WITH 1
INCREMENT BY 1
ORDER
CACHE 20;

-- CREATE SEQUENCE for sharded database
CREATE SEQUENCE shard_seq
START WITH 1
INCREMENT BY 1
CACHE 10000
NOORDER;

-- CREATE SEQUENCE with session-specific caching
CREATE SEQUENCE session_seq
START WITH 1
INCREMENT BY 1
CACHE 1
ORDER;

-- CREATE SEQUENCE for high-volume inserts
CREATE SEQUENCE high_volume_seq
START WITH 1
INCREMENT BY 1
CACHE 10000
NOORDER;

-- CREATE SEQUENCE for low-volume inserts
CREATE SEQUENCE low_volume_seq
START WITH 1
INCREMENT BY 1
CACHE 5;

-- CREATE SEQUENCE with NOCYCLE and high MAXVALUE
CREATE SEQUENCE large_nocycle_seq
START WITH 1
INCREMENT BY 1
MAXVALUE 999999999999999
NOCYCLE
CACHE 1000;

-- CREATE SEQUENCE for multi-tenant (container)
CREATE SEQUENCE container_seq
START WITH 1
INCREMENT BY 1;

-- CREATE SEQUENCE with explicit NOMINVALUE and NOMAXVALUE
CREATE SEQUENCE unbounded_seq
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE;

-- CREATE SEQUENCE for identity column simulation
CREATE SEQUENCE identity_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOORDER;

-- CREATE SEQUENCE with custom increment
CREATE SEQUENCE custom_increment_seq
START WITH 10
INCREMENT BY 7
NOCYCLE;

-- CREATE SEQUENCE for even numbers only
CREATE SEQUENCE even_seq
START WITH 2
INCREMENT BY 2
NOCYCLE;

-- CREATE SEQUENCE for odd numbers only
CREATE SEQUENCE odd_seq
START WITH 1
INCREMENT BY 2
NOCYCLE;

-- CREATE SEQUENCE with power of 2 increments
CREATE SEQUENCE power2_seq
START WITH 1
INCREMENT BY 1;  -- Would use 1, 2, 4, 8, 16... in application logic

-- CREATE SEQUENCE for UUID-like numeric IDs
CREATE SEQUENCE uuid_numeric_seq
START WITH 100000000000
INCREMENT BY 1
NOCYCLE;

-- CREATE SEQUENCE with specific business range
CREATE SEQUENCE employee_id_seq
START WITH 10000
INCREMENT BY 1
MINVALUE 10000
MAXVALUE 99999
NOCYCLE
CACHE 100;

-- CREATE SEQUENCE for fiscal year
CREATE SEQUENCE fiscal_year_seq
START WITH 2024
INCREMENT BY 1
MINVALUE 2024
NOCYCLE;

-- CREATE SEQUENCE for daily batch number
CREATE SEQUENCE daily_batch_seq
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999
CYCLE
CACHE 10;

-- CREATE SEQUENCE with SCALE (18c+) for blockchain/ledger tables
CREATE SEQUENCE ledger_seq
START WITH 1
INCREMENT BY 1
NOCACHE
ORDER
SCALE EXTEND;

-- CREATE SEQUENCE with SCALE NOEXTEND
CREATE SEQUENCE scale_noextend_seq
START WITH 1
INCREMENT BY 1
SCALE NOEXTEND;

-- CREATE SEQUENCE with SCALE EXTEND
CREATE SEQUENCE scale_extend_seq
START WITH 1
INCREMENT BY 1
SCALE EXTEND;

-- CREATE SEQUENCE with SHARD (18c+) for sharding
CREATE SEQUENCE sharded_seq
START WITH 1
INCREMENT BY 1
SHARD EXTEND;

-- CREATE SEQUENCE with SHARD NOEXTEND
CREATE SEQUENCE shard_noextend_seq
START WITH 1
INCREMENT BY 1
SHARD NOEXTEND;

-- CREATE SEQUENCE with SESSION (18c+)
CREATE SEQUENCE session_specific_seq
START WITH 1
INCREMENT BY 1
SESSION;

-- CREATE SEQUENCE with GLOBAL (18c+)
CREATE SEQUENCE global_seq
START WITH 1
INCREMENT BY 1
GLOBAL;

-- CREATE SEQUENCE for identity column (12c+)
-- This is typically done via table definition, but sequence can be created
CREATE SEQUENCE identity_backed_seq
START WITH 1
INCREMENT BY 1
NOCACHE;

-- CREATE SEQUENCE with all 18c+ features
CREATE SEQUENCE modern_seq
START WITH 1
INCREMENT BY 1
CACHE 100
ORDER
SCALE EXTEND
SESSION;

-- CREATE SEQUENCE for replication
CREATE SEQUENCE repl_seq
START WITH 1
INCREMENT BY 1
CACHE 1000
NOORDER;

-- CREATE SEQUENCE for audit trail
CREATE SEQUENCE audit_seq
START WITH 1
INCREMENT BY 1
NOCACHE
ORDER;

-- CREATE SEQUENCE for customer numbers with prefix logic
CREATE SEQUENCE customer_num_seq
START WITH 100001
INCREMENT BY 1
MINVALUE 100001
MAXVALUE 999999
NOCYCLE;

-- CREATE SEQUENCE for order numbers by year
CREATE SEQUENCE order_2024_seq
START WITH 20240001
INCREMENT BY 1
MINVALUE 20240001
MAXVALUE 20249999
NOCYCLE;

-- CREATE SEQUENCE with negative increment cycling
CREATE SEQUENCE neg_cycle_seq
START WITH 100
INCREMENT BY -1
MINVALUE 1
MAXVALUE 100
CYCLE;

-- CREATE SEQUENCE for transaction IDs
CREATE SEQUENCE transaction_id_seq
START WITH 1
INCREMENT BY 1
CACHE 5000
NOORDER;

-- CREATE SEQUENCE for reference numbers
CREATE SEQUENCE reference_seq
START WITH 1000000
INCREMENT BY 1
NOCYCLE
CACHE 100;
