-- CREATE TABLE with Oracle 23ai new datatypes
-- Testing JSON, VECTOR, and BOOLEAN datatypes

-- Table with JSON datatype (native in 23ai, not just check constraint)
CREATE TABLE products_json (
    product_id NUMBER PRIMARY KEY,
    product_name VARCHAR2(100),
    product_data JSON
);

-- Table with JSON datatype and constraints
CREATE TABLE orders_json (
    order_id NUMBER PRIMARY KEY,
    order_date DATE,
    order_details JSON,
    CONSTRAINT order_json_chk CHECK (order_details IS JSON)
);

-- Table with VECTOR datatype - basic
CREATE TABLE documents_vector (
    doc_id NUMBER PRIMARY KEY,
    title VARCHAR2(200),
    content CLOB,
    embedding VECTOR
);

-- Table with VECTOR datatype - specified dimensions
CREATE TABLE documents_vector_dim (
    doc_id NUMBER PRIMARY KEY,
    title VARCHAR2(200),
    content CLOB,
    embedding VECTOR(768)  -- 768 dimensions for semantic search
);

-- Table with VECTOR datatype - different formats
CREATE TABLE embeddings_float32 (
    id NUMBER PRIMARY KEY,
    vec_data VECTOR(1536, FLOAT32)
);

CREATE TABLE embeddings_float64 (
    id NUMBER PRIMARY KEY,
    vec_data VECTOR(1536, FLOAT64)
);

CREATE TABLE embeddings_int8 (
    id NUMBER PRIMARY KEY,
    vec_data VECTOR(128, INT8)
);

CREATE TABLE embeddings_binary (
    id NUMBER PRIMARY KEY,
    vec_data VECTOR(16, BINARY)
);

-- Table with BOOLEAN datatype (new native type in 23ai)
CREATE TABLE feature_flags (
    flag_id NUMBER PRIMARY KEY,
    flag_name VARCHAR2(100),
    is_enabled BOOLEAN DEFAULT FALSE,
    is_beta BOOLEAN,
    created_date TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Table with multiple new 23ai datatypes combined
CREATE TABLE ai_products (
    product_id NUMBER PRIMARY KEY,
    product_name VARCHAR2(100),
    is_active BOOLEAN DEFAULT TRUE,
    product_metadata JSON,
    description_embedding VECTOR(768),
    image_embedding VECTOR(512)
);

-- Table with BOOLEAN in constraints
CREATE TABLE users_with_flags (
    user_id NUMBER PRIMARY KEY,
    username VARCHAR2(50),
    is_admin BOOLEAN DEFAULT FALSE,
    is_verified BOOLEAN NOT NULL,
    can_post BOOLEAN,
    CHECK (is_admin = TRUE OR can_post = TRUE)
);

-- Table with JSON and identity column
CREATE TABLE customers_modern (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR2(100),
    contact_info JSON,
    preferences JSON,
    is_premium BOOLEAN DEFAULT FALSE
);

-- IF NOT EXISTS with new datatypes
CREATE TABLE IF NOT EXISTS analytics_data (
    id NUMBER PRIMARY KEY,
    metrics JSON,
    feature_vector VECTOR(256),
    is_processed BOOLEAN DEFAULT FALSE
);
